name: forum
description: "forum for Starfish"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.3
  dynamic_color: ^1.8.1

  dio: ^5.3.2
  html: ^0.15.4
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.4.1
  rxdart: ^0.27.7
  nil: ^1.1.1
  drift: 2.30.1
  drift_flutter: ^0.2.8
  get_it: ^9.2.0
  path_provider: 2.1.5
  easy_refresh: ^3.4.0
  url_launcher: ^6.2.5
  
  sqflite: ^2.4.2
  path: ^1.9.0
  logger: ^2.4.0
  share_plus: ^7.2.1
  hive: ^2.2.3
  flutter_secure_storage: ^10.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.30.1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/icon.png

  # fonts:
    # - family: Montserrat
    #   fonts:
    #     - asset: fonts/Montserrat-Medium.ttf
    #     - asset: fonts/Montserrat-Regular.ttf 

# 应用图标配置
flutter_launcher_icons:
  # 为 Android 配置图标
  android: true
  # 为 iOS 配置图标
  ios: true
  # 指定图标图片路径
  image_path: "assets/images/icon.png"
  # android min sdk min:16, default 21
  # min_sdk_android: 21