name: Flutter Release Build CI/CD

# Reference: https://xmaihh.github.io/blog/2024/07/26/yong-yu-gou-jian-he-fa-bu-flutter-ying-yong-cheng-xu-de-github-actions-gong-zuo-liu-cheng/
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build_env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Version Number
        id: generate_version
        run: |
          if [[ ${{ github.ref }} == refs/tags/* ]]; then
            TAG_VERSION=$(echo ${{ github.ref }} | sed -E 's/^refs\/tags\/(v)?//')
            echo "This is a tag release: $TAG_VERSION"
          
          elif [[ ${{ github.ref }} == refs/heads/* ]]; then
            TAG_VERSION=$(echo ${{ github.ref }} | sed -E 's/^refs\/heads\///' | sed 's/\//-/g')
            echo "This is a branch push: $TAG_VERSION"
          
          elif [[ ${{ github.ref }} == refs/pull/* ]]; then
            PR_NUMBER=$(echo ${{ github.ref }} | sed -E 's/^refs\/pull\/([0-9]+)\/merge$/\1/')
            TAG_VERSION="pr-$PR_NUMBER"
            echo "This is a Pull Request: $TAG_VERSION"
          
          else
            TAG_VERSION=$(echo ${{ github.ref }} | sed 's/\//-/g')
            echo "This is another trigger: $TAG_VERSION"
          fi
          echo "TAG_VERSION=$TAG_VERSION" 
          COMMIT_COUNT=$(git rev-list --count HEAD)
          SHORT_HASH=$(git rev-parse --short HEAD)
          BUILD_VERSION="${COMMIT_COUNT}"
          echo "BUILD_VERSION=${BUILD_VERSION}" >> $GITHUB_OUTPUT
          echo "Generated BUILD_VERSION: ${BUILD_VERSION}"
        shell: bash

      - name: Update version in pubspec.yaml
        id: update_version_in_pubspec
        run: |
          MAIN_VERSION=$(grep "^version:" pubspec.yaml | sed -E 's/version: ([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "MAIN_VERSION=${MAIN_VERSION}"
          
          FULL_VERSION="${MAIN_VERSION}+${{ steps.generate_version.outputs.BUILD_VERSION }}"
          echo "FULL_VERSION=${FULL_VERSION}"
          
          sed -i "s/^version: .*/version: ${FULL_VERSION}/" pubspec.yaml
          echo "Updated pubspec.yaml content:"
          cat pubspec.yaml
          
          if grep -q "^version: ${FULL_VERSION}" pubspec.yaml; then
            echo "Version updated successfully to ${FULL_VERSION}"
          else
            echo "Failed to update version"
            echo "Current version line:"
            grep "^version:" pubspec.yaml
            exit 1
          fi
          
        shell: bash

      - name: Upload updated pubspec.yaml
        uses: actions/upload-artifact@v4
        with:
          name: build_env_files
          path: |
            pubspec.yaml
            _build_env.config

  build_app:
    needs: build_env
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - name: android
            os: ubuntu-latest
          - name: android-aab
            os: ubuntu-latest
          - name: linux
            os: ubuntu-latest
          - name: windows
            os: windows-latest
          - name: ios
            os: macos-latest
          - name: macos
            os: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download updated pubspec.yaml
        uses: actions/download-artifact@v4
        with:
          name: build_env_files

      - name: Replace pubspec.yaml
        run: |
          ls
          cat pubspec.yaml
          pwd
          cat _build_env.config
        shell: bash

      - name: Read FULL_VERSION from _build_env.config
        id: read_build_env
        run: |
          echo "Reading version from _build_env.config..."
          FULL_VERSION=$(grep 'FULL_VERSION=' _build_env.config | cut -d '=' -f2)
          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_OUTPUT # 设置输出变量
        shell: bash

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable 

      - name: Check Flutter version
        run: flutter --version
      
      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        if: matrix.name == 'android'
        run: |
         flutter build apk --release --target-platform android-arm64 --obfuscate --split-debug-info=./symbols 

      - name: Build Android App Bundle
        if: matrix.name == 'android-aab'
        run: flutter build appbundle

      - name: Build Linux
        if: matrix.name == 'linux'
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
          flutter build linux

      - name: Build Windows
        if: matrix.name == 'windows'
        run: flutter build windows

      - name: Build iOS
        if: matrix.name == 'ios'
        run: flutter build ios --release --no-codesign

      - name: Build macOS
        if: matrix.name == 'macos'
        run: flutter build macos

      - name: Compress Build
        run: |
          if [ "${{ matrix.name }}" = "android" ]; then
            mv build/app/outputs/flutter-apk/app-release.apk ./app-release-all-${{ steps.read_build_env.outputs.FULL_VERSION }}.apk
            mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk ./app-release-arm64-v8a-${{ steps.read_build_env.outputs.FULL_VERSION }}.apk
          elif [ "${{ matrix.name }}" = "linux" ]; then
            zip -r linux-release-${{ steps.read_build_env.outputs.FULL_VERSION }}.zip build/linux/x64/release/bundle
          elif [ "${{ matrix.name }}" = "windows" ]; then
            powershell Compress-Archive build/windows/x64/runner/Release windows-release-${{ steps.read_build_env.outputs.FULL_VERSION }}.zip
          elif [ "${{ matrix.name }}" = "ios" ]; then
            mkdir Payload
            cp -r build/ios/iphoneos/Runner.app Payload/
            zip -r ios-release-${{ steps.read_build_env.outputs.FULL_VERSION }}.ipa Payload/
            zip -r ios-release-${{ steps.read_build_env.outputs.FULL_VERSION }}.zip build/ios/iphoneos
          elif [ "${{ matrix.name }}" = "macos" ]; then
            zip -r macos-release-${{ steps.read_build_env.outputs.FULL_VERSION }}.zip build/macos/Build/Products/Release
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-artifact
          path: |
            *.apk
            *.aab
            *.ipa
            *.zip
          if-no-files-found: error

  release:
    needs: build_app
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Read FULL_VERSION from _build_env.config
        id: read_build_env
        run: |
          echo "Reading version from _build_env.config..."
          FULL_VERSION=$(grep 'FULL_VERSION=' artifacts/build_env_files/_build_env.config | cut -d '=' -f2)
          echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_build_env.outputs.FULL_VERSION }}
          release_name: Release ${{ steps.read_build_env.outputs.FULL_VERSION }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for artifact in artifacts/*/*.{apk,aab,ipa,zip}
          do
            if [ -f "$artifact" ]; then
              asset_name=$(basename "$artifact")
              echo "Uploading $asset_name"
              curl --fail -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Content-Type: $(file -b --mime-type $artifact)" \
                --data-binary @"$artifact" \
                "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.id }}/assets?name=$asset_name"
            fi
          done
